---

- name: Write the k0s token file on worker
  template:
    src: worker-token.j2
    dest: "{{ k0s_config_dir }}/worker-token"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: Create k0s worker service with install command
  register: install_worker_cmd
  command: k0s install worker --token-file {{ k0s_config_dir }}/worker-token {{ extra_args | default(omit) }}
  args:
    creates: /etc/systemd/system/k0sworker.service
  changed_when: install_worker_cmd | length > 0

- name: Enable and check k0s service
  become: true
  systemd:
    name: k0sworker
    daemon_reload: yes
    state: restarted
    enabled: yes
